#!/bin/bash

set -e

defaults write com.apple.desktopservices DSDontWriteNetworkStores true
defaults write com.apple.finder AppleShowAllFiles YES

mkdir -p ~/.config/alacritty
mkdir -p ~/.config/nvim/colors

ln -sf ~/my/dots/bashrc ~/.bashrc
ln -sf ~/my/dots/tmux.conf ~/.tmux.conf
ln -sf ~/my/dots/bash_profile ~/.bash_profile

ln -sf ~/my/dots/init.vim ~/.config/nvim/init.vim
ln -sf ~/my/dots/mycolors.vim ~/.config/nvim/colors/mycolors.vim
ln -sf ~/my/dots/alacritty.yml ~/.config/alacritty/alacritty.yml

# install google-cloud-sdk and move to ~/google-cloud-sdk
# source path in profile_bash

# install vim plug for neovim if it doesn't exist
if [ ! -f ~/.local/share/nvim/site/autoload/plug.vim ]; then
  curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs \
  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi
