#!/bin/bash

set -e

my=$(dirname "$0")
echo $my

data_home="${XDG_DATA_HOME:-$HOME/.local/share}"
config_home="${XDG_CONFIG_HOME:-$HOME/.config}"

# as per homebrew post install instructions
homebrew() {
  echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> ~/.zprofile
  eval "$(/opt/homebrew/bin/brew shellenv)"
}

# brew packages to install
echo 'brew install these:'
echo 'neovim exa fd rg jq'

renew() {
	name=$1
	case "$2" in
	"config")
		rm -rf ${config_home}/${name}
		mkdir -p ${config_home}/${name}
		;;
	*)
		printf "usage: renew <name> <type>"
		;;
	esac
}

cp $my/zshrc ~/.zshrc
renew lf config
cp $my/lfrc ${config_home}/lf

renew alacritty config
cp $my/alacritty.yml ${config_home}/alacritty
renew nvim config
cp $my/init.vim ${config_home}/nvim
