#!/bin/bash

set -e

my=$(dirname "$0")
echo $my

data_home="${XDG_DATA_HOME:-$HOME/.local/share}"
config_home="${XDG_CONFIG_HOME:-$HOME/.config}"

macos() {
	defaults write com.apple.desktopservices DSDontWriteNetworkStores true
	defaults write com.apple.finder AppleShowAllFiles YES
	# fd -H '^\.DS_Store$' ~ -tf -X rm
}

renew() {
	name=$1
	case "$2" in
	"config")
		rm -rf ${config_home}/${name}
		mkdir -p ${config_home}/${name}
		;;
	*)
		printf "usage: renew <name> <type>"
		;;
	esac
}

macos
cp $my/zshrc ~/.zshrc

renew lf config
cp $my/lfrc ${config_home}/lf

renew alacritty config
cp $my/alacritty.yml ${config_home}/alacritty
# TODO
# https://tldp.org/HOWTO/Text-Terminal-HOWTO-16.html
# infocmp alacritty
# sudo tic -xe alacritty,alacritty-direct extra/alacritty.info

renew nvim config
cp $my/init.vim ${config_home}/nvim

vimplug="${data_home}"'/nvim/site/autoload/plug.vim'
if [ ! -f $vimplug ]; then
  plugvim='https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
  curl -fLo $vimplug --create-dirs $plugvim
fi
