name: build
on:
  push:
jobs:
  one:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    env:
      v1: the-value-of-v1
    outputs:
      v2: ${{ steps.one.outputs.v2 }}
    steps:
      - id: one
        run: |-
          echo "::set-output name=v2::the-value-of-v2"
  two:
    runs-on: ubuntu-latest
    needs: one
    strategy:
      matrix:
        protagonist: [neo, trin]
    steps:
      - run: |-
          echo "two: ${matrix.protagonist}"
  six:
    runs-on: ubuntu-latest
    needs: [one, two]
    #if: ${{ env.v1 = 'the-value-of-v1' }}
    steps:
      - run: |-
          echo "v2 = ${needs.one.outputs.v2}"
    
